# fly.toml app configuration file generated for shipping-server on 2023-07-16T14:12:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shipping-server"
primary_region = "mia"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="shipping_app"
  destination="/mnt/shipping_app"
